"
" if editing this file, reload with  :so %
"
if match($TERM, "screen")!=-1
  set term=xterm
endif


" to see all scripts loaded,  :scriptnames
source $HOME/.vim/bundles.vim

syntax on
set vb                          " visual bell
set number
set ruler
set wrap                        " set nowrap
set encoding=utf-8


" set background=dark
colorscheme jellybeans    " too dark for me -g

" highlight Visual term=reverse gui=reverse


" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
" set magic

" Whitespace 
set tabstop=4 " Display <Tab>s as 4-spaces.
set shiftwidth=4 " Shift operations should use the same amount.
set softtabstop=4 " Use a mixture of spaces and <Tab>s to complete editing operations
set list listchars=tab:▸\ ,eol:¬,trail:•

" allow toggling; test function exists b/c auto reload of this file is ON
if !exists("*TabToggle")
    function TabToggle()
        if &expandtab
            set noexpandtab
        else
            set expandtab
        endif
        endfunction
endif
nmap <F9> mz:execute TabToggle()<CR>'z
" TIP: to switch a block from tabs/spaces use :retab


" Searching
" highlight clear Search
" set incsearch                   " Makes search act like search in modern browsers
set hlsearch                    " Highlight search results
set gdefault                    " automatically set "/g" at the end of :substution commands
set ignorecase                  " Ignore case when searching
set smartcase                   " When searching try to be smart about cases 
nnoremap / /\v
vnoremap / /\v

" Auto formatting
set autoindent " automatically indent text
set formatoptions+=n1 " add formatting numbered list to autoformat

" Spelling options -- this highlights waaay too much
" set spell spelllang=en_us

" Moving around windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"Misc
set ttyfast " using a fast terminal
nnoremap ; :
inoremap jj <ESC>


" to use jsbeautify (works only on *.js files)
" <leader>ff
" where <leader> is a backslash


" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,*.swp,.svn,vendor/gems/*


" see below
" set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l
set laststatus=2                    " Always show the status line


" Remember last location in file
" if has("autocmd")
"  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
"    \| exe "normal g'\"" | endif
"endif

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" highlight reverse

" remap <F1> to turning off search highlighting (default: help)
map <F1> :nohl<CR>
imap <F1> <ESC>:nohl<CR> i

" Use modeline overrides
set modeline
set modelines=10

" set the number of undos
" undolevels 99
set ul=99

" Directories for swp files
" set backupdir=$HOME/.vim/backup
" set directory=$HOME/.vim/backup

if version >= 703
  set undofile
  set undodir=$HOME/.vim/undo
endif

" Reformat the current paragraph according to current 'textwidth' with ^]
nmap <C-]> gqap
vmap <C-]> gq
imap <C-]> <C-O>gqap

" Tabs
map <Leader>tp :tabp<CR>
map <Leader>tn :tabnext<CR>

" Show (partial) command in the status line
set showcmd

" Tagbar Configuration
nmap <Leader>tb :TagbarToggle<CR>
" Auto-focus on open, close on selection
let g:tagbar_autoclose = 1


"
" pathogen autoloading
" 
call pathogen#infect()


" autocmd vimenter * NERDTree           " add Nerdtree at startup
" nerdtree with ctrl-n
map <C-n> :NERDTreeToggle<CR>
map :nt :NERDTreeToggle<CR>

" prevent accidental :Q going in to EX mode
map Q :q

set tabpagemax=10


"""""" PERL """"""""""

" check perl code with :make
autocmd FileType perl set makeprg=perl\ -c\ %\ $*

" 
" perl module scaffold
autocmd BufNewFile  *.pm        0r ~/.vim/skeleton.pm

" let g:Perl_BraceOnNewLine     = "yes"

"  don't like/understand these!? 
" let perl_fold           = 1
" let perl_fold_blocks    = 1
" support @{${"foo"}}
:let perl_extended_vars = 1

:filetype plugin on
let g:Perl_AuthorName      = 'Gregory Coleman'
let g:Perl_AuthorRef       = 'gleeco'
let g:Perl_Email           = 'gleeco@cloudflare.com'
let g:Perl_Company         = 'Cloudlare'
let g:Perl_BraceOnNewLine   = "yes"

" fix so that mouse-button (middle) paste during insert just works
" ie. paste with a comment will still keep indenting by default;
" but hitting <F7> before the paste will do the right thing. 
"
set nopaste
nmap <F7> :set paste! paste?<CR>
imap <F7> <C-o>:set paste!<CR>
vmap <F7> <Esc>:set paste!<CR>gv
nnoremap <MiddleMouse> i<MiddleMouse>
vnoremap <MiddleMouse> s<MiddleMouse>
set pastetoggle=<F7> mouse=rnv

set ttymouse=xterm2
set mouse=a
set t_Co=256 "tell the term has 256 colors


" this is an inotify-like reloader for .vimrc
augroup myvimrc
    au!
    au BufWritePost .vimrc, so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END
